blank_issues_enabled: false
contact_links:
  - {name: "История версий", url: "https://github.com/Serka76/plex-rename/blob/main/README.md", about: "Смотрите раздел History в README — возможно, это уже исправлено"}
